/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.departamentos.vistas;

import com.example.departamentos.DepartamentosApplication;
import com.example.departamentos.SpringContext;
import com.example.departamentos.modelos.Departamento;
import com.example.departamentos.modelos.Municipio;
import com.example.departamentos.repositorios.RepositorioDepartamento;
import com.example.departamentos.repositorios.RepositorioMunicipio;
import java.util.List;
import java.util.Optional;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.springframework.core.annotation.AnnotatedElementUtils;

/**
 *
 * @author PC
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    RepositorioDepartamento repositorioDepartamento;
    RepositorioMunicipio repositorioMunicipio;
    
    public Ventana() {
        DepartamentosApplication.iniciarSpring();
        repositorioDepartamento = SpringContext.getBean(RepositorioDepartamento.class);
        repositorioMunicipio = SpringContext.getBean(RepositorioMunicipio.class);
        initComponents();
        agregarListenerCampoCodigoDepartamento();
        agregarListenerCampoCodigoMunicipio();
    }
    
    public void agregarListenerCampoCodigoMunicipio() {
        campoCodigoMunicipio.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                Long codigo  = Long.parseLong(campoCodigoMunicipio.getText());
                Optional<Municipio> resultado = repositorioMunicipio.findById(codigo);
                if (resultado.isPresent()) {
                    Municipio miunicipioEncontrado = resultado.get();
                    campoNombreMunicipio.setText(miunicipioEncontrado.getNombre());
                    campoPoblacionMunicipio.setText(Long.toString(miunicipioEncontrado.getPoblacion()));
               
                    Departamento departamentoDelMunicpio = miunicipioEncontrado.getDepartamento();
                    campoCodigo.setText(Long.toString(departamentoDelMunicpio.getCodigo()));
                    //campoNombre.setText(departamentoDelMunicpio.getNombre());
                    //campoCapital.setText(departamentoDelMunicpio.getCapital());
                } else {
                    mensajes.setText("Municipio no encontrado");
                    campoNombreMunicipio.setText("");
                    campoPoblacionMunicipio.setText("");
                }
                
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                
            }
        });
    }
    
    
    public void agregarListenerCampoCodigoDepartamento() {
        campoCodigo.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                Long codigo  = Long.parseLong(campoCodigo.getText());
                Optional<Departamento> resultado = repositorioDepartamento.findById(codigo);
                if (resultado.isPresent()) {
                    Departamento departamentoEncontrado = resultado.get();
                    campoNombre.setText(departamentoEncontrado.getNombre());
                    campoCapital.setText(departamentoEncontrado.getCapital());
                } else {
                    mensajes.setText("Departamento no encontrado");
                    campoNombre.setText("");
                    campoCapital.setText("");
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                System.out.println("se borro algo");
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                System.out.println("Algo cmabio");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoCapital = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mensajes = new javax.swing.JLabel();
        botonEliminarDepartamento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoCodigoMunicipio = new javax.swing.JTextField();
        campoNombreMunicipio = new javax.swing.JTextField();
        campoPoblacionMunicipio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botonAgregarMunicipio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        campoCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCapitalActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Depeartamento");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Capital");

        botonEliminarDepartamento.setText("Eliminar");
        botonEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarDepartamentoActionPerformed(evt);
            }
        });

        jLabel5.setText("Municipios");

        jLabel6.setText("Nombre");

        jLabel7.setText("Poblacion");

        campoCodigoMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoMunicipioActionPerformed(evt);
            }
        });

        campoPoblacionMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPoblacionMunicipioActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo");

        botonAgregarMunicipio.setText("Agregar");
        botonAgregarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMunicipioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                        .addComponent(mensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminarDepartamento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoPoblacionMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6))
                                    .addGap(75, 75, 75))
                                .addComponent(campoNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoCodigoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarMunicipio))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCodigoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPoblacionMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonEliminarDepartamento)
                    .addComponent(botonAgregarMunicipio))
                .addGap(18, 18, 18)
                .addComponent(mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Long codigo = Long.parseLong(campoCodigo.getText());
        String nombre = campoNombre.getText();
        String capital = campoCapital.getText();
        Departamento d = new Departamento(codigo, nombre, capital);
        repositorioDepartamento.save(d);
        mensajes.setText("Departamento creado exitosamente");
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void campoCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCapitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCapitalActionPerformed

    private void botonEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarDepartamentoActionPerformed
        // TODO add your handling code here:
        //Long codigo = Long.parseLong(campoCodigo.getText());
        //repositorioDepartamento.deleteById(codigo);
        String nombre = campoNombre.getText();
        List<Departamento> departamentos = repositorioDepartamento.findAll();
        Long codigoDepartamento = null;
        
        for (Departamento departamento: departamentos) {
            if (departamento.getNombre().equals(nombre)) {
                codigoDepartamento = departamento.getCodigo();
                break;
            }
        }
        
        if (codigoDepartamento != null) {
            repositorioDepartamento.deleteById(codigoDepartamento);
            mensajes.setText("Departamento eliminado correctamente");
        } else {
            mensajes.setText("Departamento " + nombre + "no encontrado");
        }
    }//GEN-LAST:event_botonEliminarDepartamentoActionPerformed

    private void campoCodigoMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoMunicipioActionPerformed

    private void campoPoblacionMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPoblacionMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPoblacionMunicipioActionPerformed

    private void botonAgregarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregarMunicipio;
    private javax.swing.JButton botonEliminarDepartamento;
    private javax.swing.JTextField campoCapital;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoCodigoMunicipio;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNombreMunicipio;
    private javax.swing.JTextField campoPoblacionMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mensajes;
    // End of variables declaration//GEN-END:variables
}
